# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.4

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/liwinux/personal/libtracex

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/liwinux/personal/libtracex

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/liwinux/personal/libtracex/CMakeFiles /home/liwinux/personal/libtracex//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/liwinux/personal/libtracex/CMakeFiles 0
.PHONY : all

# The main codegen target
codegen: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/liwinux/personal/libtracex/CMakeFiles /home/liwinux/personal/libtracex//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen
	$(CMAKE_COMMAND) -E cmake_progress_start /home/liwinux/personal/libtracex/CMakeFiles 0
.PHONY : codegen

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tx_tracer

# Build rule for target.
tx_tracer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tx_tracer
.PHONY : tx_tracer

# fast build rule for target.
tx_tracer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tx_tracer.dir/build.make CMakeFiles/tx_tracer.dir/build
.PHONY : tx_tracer/fast

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tx_tracer.dir/build.make CMakeFiles/tx_tracer.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tx_tracer.dir/build.make CMakeFiles/tx_tracer.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tx_tracer.dir/build.make CMakeFiles/tx_tracer.dir/main.c.s
.PHONY : main.c.s

src/tracex_core.o: src/tracex_core.c.o
.PHONY : src/tracex_core.o

# target to build an object file
src/tracex_core.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tx_tracer.dir/build.make CMakeFiles/tx_tracer.dir/src/tracex_core.c.o
.PHONY : src/tracex_core.c.o

src/tracex_core.i: src/tracex_core.c.i
.PHONY : src/tracex_core.i

# target to preprocess a source file
src/tracex_core.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tx_tracer.dir/build.make CMakeFiles/tx_tracer.dir/src/tracex_core.c.i
.PHONY : src/tracex_core.c.i

src/tracex_core.s: src/tracex_core.c.s
.PHONY : src/tracex_core.s

# target to generate assembly for a file
src/tracex_core.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tx_tracer.dir/build.make CMakeFiles/tx_tracer.dir/src/tracex_core.c.s
.PHONY : src/tracex_core.c.s

src/tracex_debug.o: src/tracex_debug.c.o
.PHONY : src/tracex_debug.o

# target to build an object file
src/tracex_debug.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tx_tracer.dir/build.make CMakeFiles/tx_tracer.dir/src/tracex_debug.c.o
.PHONY : src/tracex_debug.c.o

src/tracex_debug.i: src/tracex_debug.c.i
.PHONY : src/tracex_debug.i

# target to preprocess a source file
src/tracex_debug.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tx_tracer.dir/build.make CMakeFiles/tx_tracer.dir/src/tracex_debug.c.i
.PHONY : src/tracex_debug.c.i

src/tracex_debug.s: src/tracex_debug.c.s
.PHONY : src/tracex_debug.s

# target to generate assembly for a file
src/tracex_debug.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tx_tracer.dir/build.make CMakeFiles/tx_tracer.dir/src/tracex_debug.c.s
.PHONY : src/tracex_debug.c.s

src/tracex_errno.o: src/tracex_errno.c.o
.PHONY : src/tracex_errno.o

# target to build an object file
src/tracex_errno.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tx_tracer.dir/build.make CMakeFiles/tx_tracer.dir/src/tracex_errno.c.o
.PHONY : src/tracex_errno.c.o

src/tracex_errno.i: src/tracex_errno.c.i
.PHONY : src/tracex_errno.i

# target to preprocess a source file
src/tracex_errno.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tx_tracer.dir/build.make CMakeFiles/tx_tracer.dir/src/tracex_errno.c.i
.PHONY : src/tracex_errno.c.i

src/tracex_errno.s: src/tracex_errno.c.s
.PHONY : src/tracex_errno.s

# target to generate assembly for a file
src/tracex_errno.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tx_tracer.dir/build.make CMakeFiles/tx_tracer.dir/src/tracex_errno.c.s
.PHONY : src/tracex_errno.c.s

src/tracex_event.o: src/tracex_event.c.o
.PHONY : src/tracex_event.o

# target to build an object file
src/tracex_event.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tx_tracer.dir/build.make CMakeFiles/tx_tracer.dir/src/tracex_event.c.o
.PHONY : src/tracex_event.c.o

src/tracex_event.i: src/tracex_event.c.i
.PHONY : src/tracex_event.i

# target to preprocess a source file
src/tracex_event.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tx_tracer.dir/build.make CMakeFiles/tx_tracer.dir/src/tracex_event.c.i
.PHONY : src/tracex_event.c.i

src/tracex_event.s: src/tracex_event.c.s
.PHONY : src/tracex_event.s

# target to generate assembly for a file
src/tracex_event.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tx_tracer.dir/build.make CMakeFiles/tx_tracer.dir/src/tracex_event.c.s
.PHONY : src/tracex_event.c.s

src/tracex_header.o: src/tracex_header.c.o
.PHONY : src/tracex_header.o

# target to build an object file
src/tracex_header.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tx_tracer.dir/build.make CMakeFiles/tx_tracer.dir/src/tracex_header.c.o
.PHONY : src/tracex_header.c.o

src/tracex_header.i: src/tracex_header.c.i
.PHONY : src/tracex_header.i

# target to preprocess a source file
src/tracex_header.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tx_tracer.dir/build.make CMakeFiles/tx_tracer.dir/src/tracex_header.c.i
.PHONY : src/tracex_header.c.i

src/tracex_header.s: src/tracex_header.c.s
.PHONY : src/tracex_header.s

# target to generate assembly for a file
src/tracex_header.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tx_tracer.dir/build.make CMakeFiles/tx_tracer.dir/src/tracex_header.c.s
.PHONY : src/tracex_header.c.s

src/tracex_obj.o: src/tracex_obj.c.o
.PHONY : src/tracex_obj.o

# target to build an object file
src/tracex_obj.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tx_tracer.dir/build.make CMakeFiles/tx_tracer.dir/src/tracex_obj.c.o
.PHONY : src/tracex_obj.c.o

src/tracex_obj.i: src/tracex_obj.c.i
.PHONY : src/tracex_obj.i

# target to preprocess a source file
src/tracex_obj.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tx_tracer.dir/build.make CMakeFiles/tx_tracer.dir/src/tracex_obj.c.i
.PHONY : src/tracex_obj.c.i

src/tracex_obj.s: src/tracex_obj.c.s
.PHONY : src/tracex_obj.s

# target to generate assembly for a file
src/tracex_obj.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tx_tracer.dir/build.make CMakeFiles/tx_tracer.dir/src/tracex_obj.c.s
.PHONY : src/tracex_obj.c.s

src/tracex_utils.o: src/tracex_utils.c.o
.PHONY : src/tracex_utils.o

# target to build an object file
src/tracex_utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tx_tracer.dir/build.make CMakeFiles/tx_tracer.dir/src/tracex_utils.c.o
.PHONY : src/tracex_utils.c.o

src/tracex_utils.i: src/tracex_utils.c.i
.PHONY : src/tracex_utils.i

# target to preprocess a source file
src/tracex_utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tx_tracer.dir/build.make CMakeFiles/tx_tracer.dir/src/tracex_utils.c.i
.PHONY : src/tracex_utils.c.i

src/tracex_utils.s: src/tracex_utils.c.s
.PHONY : src/tracex_utils.s

# target to generate assembly for a file
src/tracex_utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tx_tracer.dir/build.make CMakeFiles/tx_tracer.dir/src/tracex_utils.c.s
.PHONY : src/tracex_utils.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... codegen"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... tx_tracer"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/tracex_core.o"
	@echo "... src/tracex_core.i"
	@echo "... src/tracex_core.s"
	@echo "... src/tracex_debug.o"
	@echo "... src/tracex_debug.i"
	@echo "... src/tracex_debug.s"
	@echo "... src/tracex_errno.o"
	@echo "... src/tracex_errno.i"
	@echo "... src/tracex_errno.s"
	@echo "... src/tracex_event.o"
	@echo "... src/tracex_event.i"
	@echo "... src/tracex_event.s"
	@echo "... src/tracex_header.o"
	@echo "... src/tracex_header.i"
	@echo "... src/tracex_header.s"
	@echo "... src/tracex_obj.o"
	@echo "... src/tracex_obj.i"
	@echo "... src/tracex_obj.s"
	@echo "... src/tracex_utils.o"
	@echo "... src/tracex_utils.i"
	@echo "... src/tracex_utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

