#ifndef __TRACE_PARSER_ERRNO_H__
#define __TRACE_PARSER_ERRNO_H__

#define TRACE_PARSER_MEM_ERR                    1
#define TRACE_PARSER_INVALID_PTR                2
#define TRACE_PARSER_FILE_OP_ERROR              3
#define TRACE_PARSER_TRACE_FILE_NOT_FOUND       4
#define TRACE_PARSER_EMPTY_TRACE_FILE           5
#define TRACE_PARSER_FILE_TOO_BIG               6
#define TRACE_PARSER_INVALID_TRACE_SIZE         7
#define TRACE_PARSER_INVALID_MAGIC_NUMBER       8
#define TRACE_PARSER_CORRUPTED_CTRL_HEADER      9
#define TRACE_PARSER_CORRUPTED_OBJECTS          10

#endif
