#ifndef __TRACEX_LABELS_ERRNO_H__
#define __TRACEX_LABELS_ERRNO_H__

typedef enum {
	TRACEX_LABELS_SUCCESS,
	TRACEX_LABELS_ALLOC_FAILURE,
    TRACEX_LABELS_BAD_INPUT_PTR,
	TRACEX_LABELS_JSON_READ_FAILURE,
	TRACEX_LABELS_JSON_NOT_FOUND,
	TRACEX_LABELS_JSON_EMPTY,
	TRACEX_LABELS_JSON_ALLOC_FAILURE,
	TRACEX_LABELS_JSON_PARSING_FAILURE,
	TRACEX_LABELS_ERRNO_COUNT
} tracex_labels_ret_t;

const char *tracex_labels_strerror(tracex_labels_ret_t tracex_error);
#endif