#ifndef TRACEX_ERRNO_H
#define TRACEX_ERRNO_H

typedef enum
{
    TRACEX_SUCCESS,
    TRACEX_ALLOC_FAILURE,
    TRACEX_NOT_INIT,
    TRACEX_INIT_FAILURE,
    TRACEX_BAD_INPUT_PTR,
    TRACEX_CALLBACK_REGISTER_FAILURE,
    TRACEX_HEADER_NOT_VALID,
    TRACEX_NEED_MORE,
    TRACEX_NULL_LENGTH,
    TRACEX_HEADER_BAD_OFFSET_START,
    TRACEX_OBJECT_BAD_OFFSET_START,
    TRACEX_OBJECT_REGISTRY_INVALID,
    TRACEX_OBJECT_INVALID,
    TRACEX_OBJECT_DUPLICATE,
    TRACEX_OBJ_ITER_END,
    TRACEX_OBJ_ITER_INVALID,
    TRACEX_EVENT_TRACE_BUFFER_INVALID,
    TRACEX_EVENT_INVALID,
    TRACEX_ERRNO_COUNT

} tracex_ret_t;


const char *TRACEX_strerror(tracex_ret_t tracex_error);

#endif
